# Generated by Django 5.1.7 on 2025-03-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='chat_user',
        ),
    ]
